version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sensor_db
      POSTGRES_USER: sensor_user
      POSTGRES_PASSWORD: sensor_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build:
      context: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://sensor_user:sensor_pass@db:5432/sensor_db
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data: